# Copyright (c) 2022 Cloudflare, Inc. All rights reserved.
# SPDX-License-Identifier: BSD-3-Clause
---
version: "3.3"
networks:
  dap_network:
    driver: bridge
services:
  leader:
    networks:
      - dap_network
    ports:
      - "8787"
    build:
      context: .
      dockerfile: daphne_worker_test/docker/miniflare.Dockerfile
    command:
      - "--wrangler-env=leader"
      - "--port=8787"
      - "--global-random"
  helper:
    networks:
      - dap_network
    ports:
      - "8788"
    build:
      context: .
      dockerfile: daphne_worker_test/docker/miniflare.Dockerfile
    command:
      - "--wrangler-env=helper"
      - "--port=8788"
      - "--global-random"
  test:
    networks:
      - dap_network
    build:
      context: .
      dockerfile: daphne_worker_test/docker/runtests.Dockerfile
    depends_on:
      - leader
      - helper
