# SPDX-License-Identifier: BSD-3-Clause

[package]
name = "dapf"
version = "0.3.0"
authors = [
  "Christopher Patton <cpatton@cloudflare.com>",
  "Armando Faz Hernandez <armfazh@cloudflare.com>",
]
edition = "2021"
license = "BSD-3-Clause"

[dependencies]
daphne = { path = ".." }
assert_matches = "1.5.0"
base64 = "0.21.0"
prio = "0.10.0"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.92"
url = { version = "2.3.1", features = ["serde"] }
clap = { version = "4.1.4", features = ["derive"] }
reqwest = { version = "0.11.14", features = ["blocking"] }
anyhow = "1.0.69"
tokio = { version = "1.25.0", features = ["macros", "rt"] }
